### ISSUE TITLE
my Parasempre is not training  (with sempre1.0)

### ISSUE THREAD

**Issue by SaraMitchell** [percyliang/sempre#50] opened 2015-05-20 09:12 UTC
Hi 

for training Parasempre in Free917
I used this command:
>./parasempre  @mode=train \
              @sparqlserver=localhost:3093 \
              @domain=free917 \
              @cacheserver=local

you said 'This should about an hour to complete'
but my system is in this part for 8 hours:

>   Lexicon() {
    Loading lexicon file lib/fb_data/6/unaryInfoStringAndAlignment.txt {
      Number of entries: 10780
    } [6.4s, cum. 6.5s]
    Loading lexicon file lib/fb_data/6/binaryInfoStringAndAlignment.txt {
      Number of entries: 18801
    } [2.0s, cum. 8.6s]
  } [8.6s, cum. 44s]
  Using cache LexiconFn.cache (242 entries)
  Loading phrase table {
    ParaphraseUtils.loadPhraseTable: number of entries=1264159
  } [12s, cum. 1m2s]
  TransUtis.loadDerivations: number of entries=13443
WordNet.loadWordRelation(der): skipping self-loop on tiercel#n#1
WordNet.loadWordRelation(der): skipping self-loop on tiercel#n#1
WordNet.loadWordRelation(der): skipping self-loop on unicycle#n#1
WordNet.loadWordRelation(der): skipping self-loop on township#n#1
WordNet.loadWordRelation(der): skipping self-loop on township#n#1
WordNet.loadWordRelation(der): skipping self-loop on isle#n#1
WordNet.loadWordRelation(der): skipping self-loop on isle#n#1
WordNet.loadWordRelation(der): skipping self-loop on lapidary#n#2
WordNet.loadWordRelation(der): skipping self-loop on lapidary#n#2
WordNet.loadWordRelation(der): skipping self-loop on lapidary#n#1
WordNet.loadWordRelation(der): skipping self-loop on lapidary#n#1
WordNet.loadWordRelation(der): skipping self-loop on stripper#n#3
WordNet.loadWordRelation(der): skipping self-loop on stripper#n#3
WordNet.loadWordRelation(der): skipping self-loop on interrelation#n#1
WordNet.loadWordRelation(der): skipping self-loop on interrelation#n#1
WordNet.loadWordRelation(der): skipping self-loop on bondage#n#2
WordNet.loadWordRelation(der): skipping self-loop on bondage#n#2
WordNet.loadWordRelation(der): skipping self-loop on bondage#n#2
WordNet.loadWordRelation(der): skipping self-loop on bondage#n#2
  Learner.learn() {
    Iteration 0/10 {
      Learn from parsing dataset {
        Processing parsing_iter=0.train: 512 examples {
          Examples {

Could you please tell me why?

**Comment by SaraMitchell** [comment] 2015-05-21 08:23
After 11 hours of waiting (in this sitution) I stop it
I tried once again to start,but same

**Comment by SaraMitchell** [comment] 2015-05-25 02:33
I have increased my 'swap space',and it passed after 5 mins...

**Comment by SaraMitchell** [comment] 2015-05-25 02:38
Now,I have a new error like this:
It happened after all 512 examples were read and weights were updated

> FormulaGenerationInfo=bInfo=fb:type.property.expected_type, eInfo1=fb:film.actor, count=true {
                  ParaphraseParser.parseQuestion: genQue=how many property has film actors as expected_type ?
                  SparqlExecutor.execute: (count (fb:type.property.expected_type fb:film.actor)) 
                  ParaphraseParser.parseQuestion: genQue=how many property is the expected_by of film actors ?
                }
                FormulaGenerationInfo=bInfo=fb:type.object.type, eInfo1=fb:film.actor, count=true {
                  No unary info for=(fb:type.object.type fb:type.object)
            ERROR: java.lang.RuntimeException: java.lang.NullPointerException:
fig.basic.Parallelizer.process(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.processParsingExamples(ParaphraseLearner.java:114)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:74)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:55)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.run(ParaphraseMain.java:36)
fig.exec.Execution.runWithObjArray(Unknown Source)
fig.exec.Execution.run(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.main(ParaphraseMain.java:90)
            ERROR: Caused by java.lang.NullPointerException:
edu.stanford.nlp.sempre.paraphrase.QuestionGenerator.generateQuestions(QuestionGenerator.java:144)
edu.stanford.nlp.sempre.paraphrase.QuestionGenerator.getQuestionsForFgInfo(QuestionGenerator.java:114)
edu.stanford.nlp.sempre.paraphrase.ParaphraseParser.parseQuestion(ParaphraseParser.java:81)
edu.stanford.nlp.sempre.paraphrase.ParsingExampleProcessor.process(ParsingExampleProcessor.java:41)
edu.stanford.nlp.sempre.paraphrase.ParsingExampleProcessor.process(ParsingExampleProcessor.java:16)
fig.basic.Parallelizer$1.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
2 errors, 1 warnings

**Comment by chengiant** [comment] 2015-05-27 08:32
There do have a bug when generating canonical questions using free917 as training dataset. You should add a null pointer checking code your self  to avoid the bug.

**Comment by yonatansito** [comment] 2015-05-27 20:26
Hey,
We didn't get any null pointer exceptions.
Can you please send that exact stack trace?

**Comment by yonatansito** [comment] 2015-05-28 00:13
Hi,
Thanks for spotting this bug (I wonder why in the past it didn't come up)!
The fix is:
In QuestionGenerator.getQuestionsForFgInfo(FormulaGenerationInfo fgInfo),
I changed the "if" statement to:

-----
if(fbFormulasInfo.hasOpposite(fgInfo.bInfo.formula) &&
fbFormulasInfo.getBinaryInfo(fbFormulasInfo.equivalentFormula(fgInfo.bInfo.formula))
!= null) {
-----

Since v1.0 was a tag, I created a new branch called v1.0-fix that has this
fix.

**Comment by lizuyao2010** [comment] 2015-05-31 12:18
Hi,
I am trying to assign 16G to train sempre1.0 on free917, It processed half of the training examples, but it gave me:
ERROR: java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded:
fig.basic.Parallelizer.process(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.processParsingExamples(ParaphraseLearner.java:115)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:74)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:55)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.run(ParaphraseMain.java:36)
fig.exec.Execution.runWithObjArray(Unknown Source)
fig.exec.Execution.run(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.main(ParaphraseMain.java:90)
            ERROR: Caused by java.lang.OutOfMemoryError: GC overhead limit exceeded:

How much memory should I assign to it with 8 number of threads assigned?
It seem more threads will take more memory right?

**Comment by SaraMitchell** [comment] 2015-06-02 13:35
@lizuyao2010  Increase your 'swap space'
maybe it works
I have allocated 4 gb

@yonatansito  thanks alot

**Comment by SaraMitchell** [comment] 2015-06-02 13:42
@yonatansito  it has taken timesssss to download all 'Dependences'.
Would u please tell me,what I only need to change v1.0?

**Comment by lizuyao2010** [comment] 2015-06-02 14:26
Thanks!
I used a empty cache file, then it works!
Zuyao

**Closed** 2015-06-09 14:57 UTC

**Comment by RobinCai1993** [comment] 2016-10-29 01:34
Hello? Did you solve the second error:
```
FormulaGenerationInfo=bInfo=fb:type.object.type, eInfo1=fb:film.actor, count=true {
                  No unary info for=(fb:type.object.type fb:type.object)
            ERROR: java.lang.RuntimeException: java.lang.NullPointerException:
fig.basic.Parallelizer.process(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.processParsingExamples(ParaphraseLearner.java:114)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:74)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:55)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.run(ParaphraseMain.java:36)
fig.exec.Execution.runWithObjArray(Unknown Source)
fig.exec.Execution.run(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.main(ParaphraseMain.java:90)
            ERROR: Caused by java.lang.NullPointerException:
edu.stanford.nlp.sempre.paraphrase.QuestionGenerator.generateQuestions(QuestionGenerator.java:144)
edu.stanford.nlp.sempre.paraphrase.QuestionGenerator.getQuestionsForFgInfo(QuestionGenerator.java:114)
edu.stanford.nlp.sempre.paraphrase.ParaphraseParser.parseQuestion(ParaphraseParser.java:81)
edu.stanford.nlp.sempre.paraphrase.ParsingExampleProcessor.process(ParsingExampleProcessor.java:41)
edu.stanford.nlp.sempre.paraphrase.ParsingExampleProcessor.process(ParsingExampleProcessor.java:16)
fig.basic.Parallelizer$1.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
2 errors, 1 warnings
```
I've changed the if statement like:
```
 public Set<String> getQuestionsForFgInfo(FormulaGenerationInfo fgInfo) {
    if(opts.bowGeneration) {
      return bowGenerate(fgInfo);
    }
    //generate from formula info
    Set<String> res = generateQuestions(fgInfo);
    //generate from equivalent formula if it exists
    if(fbFormulasInfo.hasOpposite(fgInfo.bInfo.formula) &&
      fbFormulasInfo.getBinaryInfo(fbFormulasInfo.equivalentFormula(fgInfo.bInfo.formula))
      != null)
    {
      FormulaGenerationInfo eqInfo = 
          new FormulaGenerationInfo(fbFormulasInfo.getBinaryInfo(fbFormulasInfo.equivalentFormula(fgInfo.bInfo.formula)),
              fgInfo.injectedInfo, fgInfo.entityInfo1, fgInfo.entityInfo2, fgInfo.uInfo, fgInfo.isCount, fgInfo.isInject, fgInfo.isUnary);
      res.addAll(generateQuestions(eqInfo));
    }
    return res;
  }
```
But it does not work... Could you give me some suggestions? Thank you!!
